# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14d2cf8427a2bc768c5d63050dfdc061dbaeafd1f40a99ceafbd4500f079b8656c9e032fc64e9649a2147e5984dba85ec0d26d21fafa4681794c7d507e86817e

test:
  secret_key_base: 5df02c8ece9eae2444d330e6446f143102648910165c43cd5046f5ee85c1ef05b00a589143fae62c04c113ce89ce3152e14151d1727135c7f930a973a847c240

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
